# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bq7uQw9cSaaQegNV6epnRiWVIaYSNZrj
"""

import pandas as pd

# Task 1
df = pd.read_csv("/content/sample_data/train.csv")
print(df.head())

# Task 2
df_1 = df.copy()
df_1['Name'] = df['Name'].str.lower()
print(df_1['Name'])

# Task 3
# Convert to int
# Make sure that int(df value) is not working anymore
df_2 = df.copy()
df_2['Fare'] = df['Fare'].astype(int)
print(df_2['Fare'])

# Task 4
df_3 = df.copy()
# mean() method is collecting (calculating) average of the data
df_3.fillna(df_3['Fare'].mean(), inplace=True)  # 平均値
display(df_3)

# Task 5
df_4 = df.copy()
display(df_4.dropna(subset=['Age'])[1:8])

# Task 6

df_5 = df.copy()

# Calculate q1, q3
q1 = df_5['Age'].quantile(q=0.25)
q3 = df_5['Age'].quantile(q=0.75)

iqr = df_5['Age'].quantile(q=0.75) - df_5['Age'].quantile(q=0.25)
print(f'q1 - q3 = {iqr}')
outlier1 = q1 - (1.5 * iqr)
outlier2 = q3 + (1.5 * iqr)
print('outlier1:\n', outlier1)
print('outlier2:\n', outlier2)
drop_index = df_5.index[df_5['Age'] <= outlier1]

# Result select values that are not including outliers
df_5[(df_5['Age'] >= outlier1) & (df_5['Age'] <= outlier2)]

# Task 7

df_6 = df.copy()

df_6['Age'].hist()